services:
  frontend:
    build:
      context: ./frontend/route-zero-enterprise
    container_name: frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend/server
    container_name: backend
    ports:
      - "3001:8080"
