#!/usr/bin/env bash

docker compose up -d && \
docker tag route-zero-enterprise-frontend elliotmb/rze-frontend:newest && \
docker push elliotmb/rze-frontend:newest

# ON AWS T2.MICRO EC2
# sudo docker container ls
# *check that no other containers are running*
#       *... if they are* sudo docker rm -f <CONTAINER_STRING>
# sudo docker pull elliotmb/rze-frontend:newest
# *requests latest image from Docker Hub*
# sudo docker run -p=80:3000 elliotmb/rze-frontend
# *starts container from image elliotmb/rze-frontend and binds port 3000 on the container to port 80 on the EC2 instance*
# current IP for the machine is http://54.166.51.165/ accessible over HTTP (:80)
