#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [main, dev]
    # Remove the line above to run when pushing to main
  pull_request:
    branches: [main, dev]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          #VALIDATE_ALL_CODEBASE: this decides whether Super Linter should lint the whole codebase or just the 
          #changes introduced with that commit. These changes are found out using git diff
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          #IGNORE_GENERATED_FILES: In case you have any files which are generated by tools, you could mark them as @generated. 
          #If this environment variable is set to true, Super Linter ignores these files. 
          IGNORE_GENERATED_FILES: false
          IGNORE_GITIGNORED_FILES: true 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}