name: Push image to my EC2

on:
  pull_request:
    branches: ['dev', 'main']

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up API key file
        run: |
          touch backend/server/src/main/resources/api_key.json
          printf "{\n  \"apiKey\": \"%s\"\n}" ${{secrets.API_KEY}} > backend/server/src/main/resources/api_key.json

      - name: Show me the file system
        run: |
          sudo apt update
          sudo apt install tree
          tree 

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "44.205.217.6"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/rze"
          SCRIPT_AFTER: |
            tmux && sudo systemctl start docker && cd ~/rze && sudo docker build -t elliotmb/rze /home/ec2-user/rze && sudo docker run -p 80:3000 -p 8080:8080 elliotmb/rze 

