name: Push_to_EC2

on: 
  push:
    branches: ['dev', 'main']

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-44-205-217-6.compute-1.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/rze"