name: Test

on:
  pull_request:
    branches: ['dev', 'main', 'feature-*']

jobs:
  frontend-test:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd frontend/route-zero-enterprise
          npm ci
          npm run build --if-present
          npm test
  spring-app-ci:
    name: Spring App CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.2'
          distribution: 'adopt'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.6
      - name: Set up API key file
        run: |
          touch backend/server/src/main/resources/api_key.json
          printf "{\n  \"apiKey\": \"%s\"\n}" ${{secrets.API_KEY}} > backend/server/src/main/resources/api_key.json
      - name: Test Build
        run: |
          mvn clean install -f backend/server
          mvn test -f backend/server
      - name: Delete API key file
        run: |
          rm backend/server/src/main/resources/api_key.json

